# See: https://www.dartlang.org/tools/pub/pubspec
name: drylib
version: 0.0.0
description: >-
  DRYlib for Dart
author: Arto Bendiken <arto@dryproject.org>
homepage: https://github.com/dryproject/drylib.dart
documentation:
dependencies:
dev_dependencies:
  test: '>=1.3.4 <2.0.0'
dependency_overrides:
environment:
 sdk: '>=2.0.0 <3.0.0'
executables:
